
spring:
  #aws⬇️
  servlet:
    multipart:
      enabled: true # 멀티파트 업로드 지원여부 (default: true)
      file-size-threshold: 0B # 파일을 디스크에 저장하지 않고 메모리에 저장하는 최소 크기 (default: 0B)
      location: /users/charming/temp # 업로드된 파일이 임시로 저장되는 디스크 위치 (default: WAS가 결정)
      max-file-size: 20MB # 한개 파일의 최대 사이즈 (default: 1MB)
      max-request-size: 300MB # 한개 요청의 최대 사이즈 (default: 10MB)

  datasource:
    username: ENC(TlaulwBRllLajYjTkCauEQ==)
    password: ENC(64fDxMDXCawegKuZFDbzkOlbuHgtfv4U)
    driver-class-name: org.mariadb.jdbc.Driver
    url: ENC(ZfqrxTBGigFdkVnsSO3vGKIm0PFAjRK382DCHI1WHDeY3+J+CQqeOz9JJ1rNs/mn4KRnj9ZHcpo=)


#    devDB
#  datasource:
#    username: ENC(9tw3qrOzQ9In8o0DZo2Id+6ohWLEj8ZL)
#    password: ENC(7xE8H8L38tpigQdQVREk7Yd1/eck19TIcxtkMwPvBho=)
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: ENC(V8aQFNv5wr4Ql3VJodqyM0NlrIhdCqh5IRPrYlMZwR2DjK7NZZihjtMQDeNr4fCpKFl812vkWJ6y8zA6cUyAVOSrjRW0W3olBqRfUO04eXrdrxEJe/H4GjToB4yRFCxH)


  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    open-in-view: false
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379

jasypt:
  encryptor:
    password: ${JASYPT_SECRET_KEY}
    bean: jasyptStringEncryptor

jwt:
  jwt-password:
    source: ENC(xwbs64JM9WVz5G5WO0xNPcFkSxEqlRUunveya2a2TiE=)

email:
  address: ENC(wCAUHlRDnSdjxSZEczI9XG3Q6BUXy+Inhi2xKIzScA8=)
  app-password: ENC(BT49Z4LzbQSP2NLoXTvebjiAYJmILhq0ScaUDE9qWuw=)

aws:
  server-url: ENC(GUpc3MWW/cmzT0P+0CoK7ZFxKSonX3QQMr9auCSmKEI=)
  new-server-url: ENC(5Uf5jgyCNS1RSm7x9mr11ril8VV0274RlmkXtc5L/K94744heMCh2g==)
  s3:
    credentials:
      access-key: ENC(3GPc4s7104mBP6+PswGBPiXzNHj/Rj+BSaArVv0yf9w=)
      secret-key: ENC(EG1UGvGC37vl4JwRD+L9BC9OD2GkR7Ndi/WW7x3QVGjs2uj7/kcvXhjJVEES45CylP97MV9gymg=)
    bucket-name: ENC(GHq5AsY5Cl8UqcGhxt0uZ+FqwAvozPZT)
    region: ENC(N2HhGgAsrLMJpKwIKsLW1KgGBZyGVt8c)

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /jba-docs.html
  version: 1.0.0

upload:
  path: /mnt/files/