
spring:
  datasource:
    username: ENC(dwj/vyhyvJGjquwmQNALlTOLF7W+TDrx)
    password: ENC(Geo4IHpXtYZNzzFrXKJSrvLMYPembAnGT7ajiPagSDg=)
    driver-class-name: org.mariadb.jdbc.Driver
    url: ENC(V8aQFNv5wr4Ql3VJodqyM0NlrIhdCqh5IRPrYlMZwR2DjK7NZZihjtMQDeNr4fCpKFl812vkWJ6y8zA6cUyAVOSrjRW0W3olBqRfUO04eXrdrxEJe/H4GjToB4yRFCxH)
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    open-in-view: false
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379

jasypt:
  encryptor:
    password: ${JASYPT_SECRET_KEY}
    bean: jasyptStringEncryptor

jwt:
  jwt-password:
    source: ENC(xwbs64JM9WVz5G5WO0xNPcFkSxEqlRUunveya2a2TiE=)
  valid-time:
    access-token: ENC(0L/0Uyraw3HqEA5603az8Q==)
    refresh-token: ENC(JW8jyHqCPkBJ8NTvex3rEmeQWe5acRiI)

email:
  address: ENC(wCAUHlRDnSdjxSZEczI9XG3Q6BUXy+Inhi2xKIzScA8=)
  app-password: ENC(BT49Z4LzbQSP2NLoXTvebjiAYJmILhq0ScaUDE9qWuw=)

